name: Build

on:
  release:
    types:
      - pusblished
      - created
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        env:
          CIBW_BEFORE_BUILD: pip install setuptools-rust
          CIBW_BEFORE_ALL_LINUX: "curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y"

          CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'

          CIBW_SKIP: cp2* pp* cp35* *win*
          CIBW_BUILD_VERBOSITY: 1

          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
